from app.routers import comments as comments_router  # noqa: F401
from app.routers import config as config_router  # noqa: F401
from app.routers import email_list as email_list_router  # noqa: F401
from app.routers import events as events_router  # noqa: F401
from app.routers import groups as groups_router  # noqa: F401
from app.routers import likes as likes_router  # noqa: F401
from app.routers import programs as programs_router  # noqa: F401
from app.routers import tags as tags_router  # noqa: F401
from app.routers import tasks as tasks_router  # noqa: F401
from app.routers import troops as troops_router  # noqa: F401
from app.routers import users as users_router  # noqa: F401
from app.routers import workspaces as workspaces_router  # noqa: F401
