"""initdb

Revision ID: 3fdbf51d5496
Revises: 
Create Date: 2025-11-09 02:26:33.326895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fdbf51d5496'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emaillist',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('email', name='uq_emaillist_email')
    )
    op.create_table('groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.CheckConstraint('char_length(name) >= 1', name='ck_group_name_min'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.CheckConstraint('char_length(name) >= 1', name='ck_tag_name_min'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_tag_name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('auth0_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('pronouns', sa.Enum('she_her', 'he_him', 'they_them', 'other', 'prefer_not_to_say', name='pronouns_enum'), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('char_length(auth0_id) >= 1', name='ck_users_auth0_min'),
    sa.CheckConstraint('char_length(name) >= 1', name='ck_users_name_min'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth0_id', name='uq_users_auth0_id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index(op.f('ix_users_auth0_id'), 'users', ['auth0_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.Enum('program', 'event', 'task', name='content_type_enum'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('char_length(name) >= 1', name='ck_content_name_min'),
    sa.CheckConstraint('like_count >= 0', name='ck_content_like_nonneg'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_memberships',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'editor', 'viewer', name='group_role_enum'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('default_meeting_weekday', sa.Enum('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', 'unknown', name='workspace_weekday_enum'), nullable=False),
    sa.Column('default_start_time', sa.Time(), nullable=False),
    sa.Column('default_end_time', sa.Time(), nullable=False),
    sa.Column('default_interval', sa.Enum('weekly', 'biweekly', 'monthly', 'yearly', 'unknown', name='workspace_event_interval_enum'), nullable=False),
    sa.Column('season_start', sa.Date(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('char_length(name) >= 1', name='ck_users_name_min'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('body', sa.String(length=5000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('char_length(body) >= 1', name='ck_comment_body_min'),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_tags',
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_id', 'tag_id')
    )
    op.create_table('programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['content.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_program_workspace_id_id')
    )
    op.create_table('troops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspace_memberships',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'editor', 'viewer', name='workspace_role_enum'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'user_id')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('start_dt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['content.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'program_id'], ['programs.workspace_id', 'programs.id'], name='fk_event_program_workspace_program', ondelete='RESTRICT', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('media', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('participant_min', sa.Integer(), nullable=True),
    sa.Column('participant_max', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id'], ['content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('troop_participation',
    sa.Column('troop_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['troop_id'], ['troops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('troop_id', 'event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('troop_participation')
    op.drop_table('tasks')
    op.drop_table('events')
    op.drop_table('workspace_memberships')
    op.drop_table('troops')
    op.drop_table('programs')
    op.drop_table('content_tags')
    op.drop_table('comments')
    op.drop_table('workspaces')
    op.drop_table('group_memberships')
    op.drop_table('content')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_auth0_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('groups')
    op.drop_table('emaillist')
    # ### end Alembic commands ###
    # drop_table leaves behind the enum types create_table made, and a second
    # upgrade then fails with "type ... already exists".
    bind = op.get_bind()
    for enum_name in (
        'workspace_role_enum',
        'workspace_event_interval_enum',
        'workspace_weekday_enum',
        'group_role_enum',
        'content_type_enum',
        'pronouns_enum',
    ):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
