"""Replace count, duration, prep_time with min/max integer range pairs.

Revision ID: 47da17d8f7dc
Revises: aeaa97f45732
Create Date: 2026-03-13 11:58:22.809975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47da17d8f7dc'
down_revision: Union[str, Sequence[str], None] = 'aeaa97f45732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('duration_min', sa.Integer(), nullable=True))
    op.add_column('content', sa.Column('duration_max', sa.Integer(), nullable=True))
    op.add_column('content', sa.Column('count_min', sa.Integer(), nullable=True))
    op.add_column('content', sa.Column('count_max', sa.Integer(), nullable=True))
    op.add_column('content', sa.Column('prep_time_min', sa.Integer(), nullable=True))
    op.add_column('content', sa.Column('prep_time_max', sa.Integer(), nullable=True))
    op.drop_column('content', 'duration')
    op.drop_column('content', 'prep_time')
    op.drop_column('content', 'count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('content', sa.Column('prep_time', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('content', sa.Column('duration', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('content', 'prep_time_max')
    op.drop_column('content', 'prep_time_min')
    op.drop_column('content', 'count_max')
    op.drop_column('content', 'count_min')
    op.drop_column('content', 'duration_max')
    op.drop_column('content', 'duration_min')
    # ### end Alembic commands ###
