"""change duration and prep_time to string

Revision ID: 7341ea425998
Revises: b263f741bc09
Create Date: 2026-02-19 19:36:16.545846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7341ea425998'
down_revision: Union[str, Sequence[str], None] = 'b263f741bc09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content', 'duration',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('content', 'prep_time',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Postgres will not cast varchar to integer without USING. Keep the first
    # run of digits, at most nine so it fits ("15-20 mín" becomes 15), and null
    # anything with none; free text like "um hálftími" has no integer to go
    # back to.
    op.alter_column('content', 'prep_time',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True,
               postgresql_using="substring(prep_time from '[0-9]{1,9}')::integer")
    op.alter_column('content', 'duration',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True,
               postgresql_using="substring(duration from '[0-9]{1,9}')::integer")
