"""add likes table, remove public field

Revision ID: 8e6eaf320920
Revises: 3fdbf51d5496
Create Date: 2025-11-23 12:40:21.089453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e6eaf320920'
down_revision: Union[str, Sequence[str], None] = '3fdbf51d5496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'content_id')
    )
    op.drop_column('content', 'public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing rows need a value before the column can be NOT NULL again.
    # False was the schema default when the field existed.
    op.add_column('content', sa.Column('public', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.execute("UPDATE content SET public = false")
    op.alter_column('content', 'public', existing_type=sa.BOOLEAN(), nullable=False)
    op.drop_table('likes')
    # ### end Alembic commands ###
