"""

Revision ID: c76a42f2e49c
Revises: 07dd9bcf0ea4
Create Date: 2026-03-15 17:42:45.181427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c76a42f2e49c'
down_revision: Union[str, Sequence[str], None] = '07dd9bcf0ea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('program_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'programs', ['program_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'program_id')
    # ### end Alembic commands ###
