"""add permissions to user, add more fields to content

Revision ID: eb93eba33650
Revises: 8e6eaf320920
Create Date: 2026-02-18 16:56:40.260014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb93eba33650'
down_revision: Union[str, Sequence[str], None] = '8e6eaf320920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('equipment', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('content', sa.Column('instructions', sa.String(length=5000), nullable=True))
    op.add_column('content', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('content', sa.Column('age', sa.String(length=50), nullable=True))
    op.add_column('content', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('content', sa.Column('count', sa.Integer(), nullable=True))
    op.add_column('content', sa.Column('price', sa.Integer(), nullable=True))
    op.drop_column('events', 'location')
    op.drop_column('tasks', 'equipment')
    permissions_enum = sa.Enum('admin', 'member', 'viewer', name='permissions_enum')
    permissions_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('permissions', permissions_enum, nullable=True))
    op.execute("UPDATE users SET permissions = 'member' WHERE permissions IS NULL")
    op.alter_column('users', 'permissions', existing_type=permissions_enum, nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'permissions')
    permissions_enum = sa.Enum('admin', 'member', 'viewer', name='permissions_enum')
    permissions_enum.drop(op.get_bind(), checkfirst=True)
    op.add_column('tasks', sa.Column('equipment', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('content', 'price')
    op.drop_column('content', 'count')
    op.drop_column('content', 'location')
    op.drop_column('content', 'age')
    op.drop_column('content', 'duration')
    op.drop_column('content', 'instructions')
    op.drop_column('content', 'equipment')
    # ### end Alembic commands ###
